### ISSUE TITLE
Merge work from various feature branches

### ISSUE THREAD

**Issue by olav-valle** [revosw/unitytest#20]

**Comment by olav-valle** [comment]
# todo's:

###new player prefab
- [ ] PlayerController script
  - [ ] Check if any functionality remains to be ported over from PlayerMovement script
  - [ ] changing input direction mid-air vs letting go of input mid-air. They work/feel differently.
  - [ ] that fucking walljump...
- [x] integrate main menu / pause
  - [x] GameManager?
  - [x] IPausable?
- [ ] integrate health script
  - [ ] healing
  - [ ] taking damage
- [ ] double check animation triggers
  - [ ] transform scale?
- [ ] RB mass, gravity, drag


###projectile:
 - [ ] being incorrectly despawned when shoot is spammed
 - [ ] sometimes not registering bounces. Collider related, probably?

### UI
 - [x] menus
 - [ ] HP counter
 - [ ] shot counter?

### Pickups
 - [ ] check that they still work with the modified playerController script
 - [ ] rewrite Health pickup to use Pickup interface

**Comment by olav-valle** [comment]
all good in the hood
